### ISSUE TITLE
New important task not marked as important

### ISSUE THREAD

**Issue by scroom** [owncloud/tasks#359]
### Steps to reproduce
1. Got to the important tasks
2. enter the text field marked with new add new important task (In german "Einen wichtigen Eintrag in "Pserönlich" hinzufügen") write the name of the task and press enter

### Expected behaviour
I'm expecting that the new task is created and marked as important as the description of the text field mentions.

### Actual behaviour
The task is created but it isn't marked as important.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** 9.0.4

**Tasks version:** 0.9.1

**Updated from an older ownCloud or fresh install:** updated

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

Do you need more information?

**Comment by raimund-schluessler** [comment]
Thanks for the report. Since I am able to reproduce this behavior, no further information is necessary. Should be fixed in the next release.

**Comment by scroom** [comment]
Thanks for your really fast response! I look forward to the new version of tasks!

**Comment by raimund-schluessler** [comment]
The bug should be fixed with #361, maybe you could test it.

**Comment by scroom** [comment]
Thanks! Sadly I can't test it (can't find the files in which you've done the changes).

**Comment by raimund-schluessler** [comment]
You would need to checkout the whole Tasks app. If you never worked with Git this is not really straightforward.

**Comment by scroom** [comment]
Do you need my test? If yes I would try to familiarize myself to git.

**Comment by scroom** [comment]
Bug is still present in the new version (0.9.3). Can I do something to help you to solve it?

**Comment by scroom** [comment]
Seems to be solved in 0.9.4. Thanks for your great work!

**Comment by raimund-schluessler** [comment]
Thanks for the feedback, good to hear.
